apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: neo4j-backup
  name: cos-secret
data:
  access_key_id: <BASE64-ACCESS-KEY_ID-REDACTED>
  secret_access_key: <BASE64-SECRET-ACCESS-KEY-REDACTED>