kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: neo4j-block-gold-dal10
  labels:
    app: ibmcloud-block-storage-plugin
    zone: dal10
provisioner: ibm.io/ibmc-block
parameters:
  billingType: hourly
  classVersion: '2'
  fsType: ext4
  iopsPerGB: '10'
  sizeRange: '[20-4000]Gi'
  type: Endurance
  region: us-south
  zone: dal10
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate